-- Constante do Role Softway
DEFINE ROLE_SOFTWAY = 

-- Constantes para Conexão
DEFINE TNS = 

-- Usuários Padrão
DEFINE SOFT_USER = 
DEFINE SOFT_PASS = 

DEFINE IO_USER = 
DEFINE IO_PASS = 

DEFINE INOUT_USER = 
DEFINE INOUT_PASS = 

DEFINE IMPORT_USER = 
DEFINE IMPORT_PASS = 

DEFINE BROKER_USER = 
DEFINE BROKER_PASS = 

DEFINE EXPORT_USER = 
DEFINE EXPORT_PASS = 

DEFINE DRAWBACK_USER = 
DEFINE DRAWBACK_PASS = 

DEFINE CAMBIO_EXP_USER = 
DEFINE CAMBIO_EXP_PASS = 

DEFINE CAMBIO_IMP_USER = 
DEFINE CAMBIO_IMP_PASS = 

DEFINE INTEGRACAO_USER = 
DEFINE INTEGRACAO_PASS = 

-- Demais Usuários
DEFINE RECOF_USER  = 
DEFINE REGESP_USER = 

-- Constantes de Tablespace
DEFINE SFW_DATA_4K    = 
DEFINE SFW_DATA_64K   = 
DEFINE SFW_DATA_128K  = 
DEFINE SFW_DATA_512K  = 
DEFINE SFW_DATA_1M    = 
DEFINE SFW_INDEX_4K   = 
DEFINE SFW_INDEX_64K  = 
DEFINE SFW_INDEX_128K = 
DEFINE SFW_INDEX_512K = 
DEFINE SFW_INDEX_1M   = 

DEFINE SFW_IO_DATA_4K    = 
DEFINE SFW_IO_DATA_64K   = 
DEFINE SFW_IO_DATA_512K  = 
DEFINE SFW_IO_DATA_1M    = 
DEFINE SFW_IO_INDEX_4K   = 
DEFINE SFW_IO_INDEX_64K  = 
DEFINE SFW_IO_INDEX_512K = 
DEFINE SFW_IO_INDEX_1M   = 

DEFINE SFW_IMPORT_DATA_4K  = 
DEFINE SFW_IMPORT_DATA_1M  = 
DEFINE SFW_IMPORT_INDEX_4K = 
DEFINE SFW_IMPORT_INDEX_1M = 

DEFINE SFW_BROKER_DATA_4K  = 
DEFINE SFW_BROKER_DATA_1M  = 
DEFINE SFW_BROKER_INDEX_4K = 
DEFINE SFW_BROKER_INDEX_1M = 

DEFINE SFW_EXPORT_DATA_4K    = 
DEFINE SFW_EXPORT_DATA_32K   = 
DEFINE SFW_EXPORT_DATA_64K   = 
DEFINE SFW_EXPORT_DATA_128K  = 
DEFINE SFW_EXPORT_DATA_512K  = 
DEFINE SFW_EXPORT_DATA_1M    = 
DEFINE SFW_EXPORT_INDEX_4K   = 
DEFINE SFW_EXPORT_INDEX_32K  = 
DEFINE SFW_EXPORT_INDEX_64K  = 
DEFINE SFW_EXPORT_INDEX_128K = 
DEFINE SFW_EXPORT_INDEX_512K = 
DEFINE SFW_EXPORT_INDEX_1M   = 

DEFINE SFW_DRAWBACK_DATA_4K    = 
DEFINE SFW_DRAWBACK_DATA_32K   = 
DEFINE SFW_DRAWBACK_DATA_64K   = 
DEFINE SFW_DRAWBACK_DATA_128K  = 
DEFINE SFW_DRAWBACK_DATA_512K  = 
DEFINE SFW_DRAWBACK_DATA_1M    = 
DEFINE SFW_DRAWBACK_INDEX_4K   = 
DEFINE SFW_DRAWBACK_INDEX_32K  = 
DEFINE SFW_DRAWBACK_INDEX_64K  = 
DEFINE SFW_DRAWBACK_INDEX_128K = 
DEFINE SFW_DRAWBACK_INDEX_512K = 
DEFINE SFW_DRAWBACK_INDEX_1M   = 

DEFINE SFW_CAMBIO_EXP_DATA_4K    =  
DEFINE SFW_CAMBIO_EXP_DATA_64K   = 
DEFINE SFW_CAMBIO_EXP_DATA_128K  = 
DEFINE SFW_CAMBIO_EXP_DATA_512K  = 
DEFINE SFW_CAMBIO_EXP_DATA_1M    = 
DEFINE SFW_CAMBIO_EXP_INDEX_4K   =
DEFINE SFW_CAMBIO_EXP_INDEX_64K  =
DEFINE SFW_CAMBIO_EXP_INDEX_128K =
DEFINE SFW_CAMBIO_EXP_INDEX_512K = 
DEFINE SFW_CAMBIO_EXP_INDEX_1M   = 

DEFINE SFW_CAMBIO_IMP_DATA_4K    = 
DEFINE SFW_CAMBIO_IMP_DATA_64K   = 
DEFINE SFW_CAMBIO_IMP_DATA_128K  = 
DEFINE SFW_CAMBIO_IMP_DATA_512K  = 
DEFINE SFW_CAMBIO_IMP_DATA_1M    = 
DEFINE SFW_CAMBIO_IMP_INDEX_4K   = 
DEFINE SFW_CAMBIO_IMP_INDEX_64K  = 
DEFINE SFW_CAMBIO_IMP_INDEX_128K = 
DEFINE SFW_CAMBIO_IMP_INDEX_512K = 
DEFINE SFW_CAMBIO_IMP_INDEX_1M   = 
